name: Handle Tweet Form Submissions

on:
  repository_dispatch:
    types: [tweet-submission]
  workflow_dispatch:
    inputs:
      content:
        description: 'Tweet content'
        required: true
      scheduled_time:
        description: 'Scheduled time (ISO format)'
        required: true
      uuid:
        description: 'Tweet UUID'
        required: true

jobs:
  process-tweet:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Process Tweet Submission
      run: |
        if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
          CONTENT="${{ github.event.client_payload.content }}"
          SCHEDULED_TIME="${{ github.event.client_payload.scheduled_time }}"
          UUID="${{ github.event.client_payload.uuid }}"
        else
          CONTENT="${{ github.event.inputs.content }}"
          SCHEDULED_TIME="${{ github.event.inputs.scheduled_time }}"
          UUID="${{ github.event.inputs.uuid }}"
        fi
        
        python scripts/process_submission.py "$CONTENT" "$SCHEDULED_TIME" "$UUID"

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/tweets/manual_tweets.csv data/tweets/master_tweets.csv
        git commit -m "Add scheduled tweet from form submission" || echo "No changes to commit"
        git push