name: Handle OAuth Callback

on:
  repository_dispatch:
    types: [oauth-callback]

jobs:
  exchange-code:
    runs-on: ubuntu-latest
    
    steps:
    - name: Exchange Code for Token
      env:
        CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
      run: |
        response=$(curl -X POST \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          https://github.com/login/oauth/access_token \
          -d "{\"client_id\":\"$CLIENT_ID\",\"client_secret\":\"$CLIENT_SECRET\",\"code\":\"${{ github.event.client_payload.code }}\"}")
        
        echo "::add-mask::$(echo $response | jq -r '.access_token')"
        echo "TOKEN=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

    - name: Return Token
      if: env.TOKEN
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const callback_url = context.payload.client_payload.callback_url;
          if (callback_url) {
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'oauth-response',
              client_payload: {
                token: process.env.TOKEN,
                state: context.payload.client_payload.state
              }
            });
          }