name: Handle OAuth Callback

on:
  repository_dispatch:
    types: [oauth-callback]

jobs:
  exchange-code:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Exchange Code
      env:
        GH_TOKEN: ${{ secrets.TWEET_MANAGER_TOKEN }}
      run: |
        response=$(curl -s -X POST \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${GH_TOKEN}" \
          https://github.com/login/oauth/access_token \
          -d "{\"client_id\":\"${{ secrets.OAUTH_CLIENT_ID }}\",\"client_secret\":\"${{ secrets.OAUTH_CLIENT_SECRET }}\",\"code\":\"${{ github.event.client_payload.code }}\"}")
        
        echo "$response" > token.json
        
    - name: Commit Token
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add token.json
        git commit -m "Add OAuth token"
        git push