name: Post Tweets
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  post-tweets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tweet poster
        env:
          IFTTT_WEBHOOK_URL: ${{ secrets.IFTTT_WEBHOOK_URL }}
        run: python update_csv.py
        
      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain data/tweets.csv | wc -l > changes.txt
          echo "changes=$(cat changes.txt)" >> $GITHUB_OUTPUT
        
      - name: Commit changes
        if: steps.check_changes.outputs.changes != '0'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/tweets.csv
          git diff --staged --quiet || git commit -m "Update tweet status [skip ci]"
          git push