name: Process Tweet Issue

on:
  issues:
    types: [opened]

jobs:
  add-to-csv:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.TWEET_MANAGER_TOKEN }}
        
    - name: Extract and Save Tweet
      run: |
        # Create data directory if it doesn't exist
        mkdir -p data
        
        # Extract info from issue body
        BODY="${{ github.event.issue.body }}"
        TWEET=$(echo "$BODY" | grep "Tweet:" | cut -d':' -f2- | xargs)
        DATE=$(echo "$BODY" | grep "Date:" | cut -d':' -f2- | xargs)
        TIME=$(echo "$BODY" | grep "Time:" | cut -d':' -f2- | xargs)
        
        # Generate ID
        ID="M$(openssl rand -hex 3)"
        TIMESTAMP="$DATE $TIME"
        
        # Add to tweets.csv in the working format
        if [ ! -f data/tweets.csv ]; then
          echo "id,timestamp,message,posted,type,scheduled_for,priority,source,raw_data" > data/tweets.csv
        fi
        echo "$ID,$TIMESTAMP,\"$TWEET\",False,manual,$TIMESTAMP,1,manual," >> data/tweets.csv
        
        # Commit and push
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add data/tweets.csv
        git commit -m "Added new tweet from issue #${{ github.event.issue.number }}"
        git push

    - name: Close Issue
      uses: peter-evans/close-issue@v3
      with:
        issue-number: ${{ github.event.issue.number }}
        comment: "Tweet added to schedule"